name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' # Specify .NET 8

    - name: Restore dependencies
      run: dotnet restore Testing.sln

    - name: Build
      run: dotnet build Testing.sln --no-restore

    - name: Free Code Coverage
      uses: SamuelCabralCruz/free-code-coverage@v0.0.13
