name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' # Specify .NET 8

    - name: Restore dependencies
      run: dotnet restore Testing.sln

    - name: Build
      run: dotnet build Testing.sln --no-restore

    - name: Run tests with coverage
      run: dotnet test Testing.sln --no-build --collect:"XPlat Code Coverage" /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./TestResults/

    - name: List all files and directories
      run: find . -type d -or -type f

    - name: Verify test results directory
      run: find . -name TestResults -exec ls -la {} \;

    - name: List TestResults directory contents
      run: ls -la ./TestResults/

    - name: Generate Code Coverage report
      id: code-coverage
      uses: barecheck/code-coverage-action@v1
      with:
        barecheck-github-app-token: ${{ secrets.BARECHECK_GITHUB_APP_TOKEN }}
        lcov-file: "./TestResults/coverage.cobertura.xml"
        base-lcov-file: "./TestResults/base-lcov.info" # Adjust this if you have a base coverage file
        send-summary-comment: true
        show-annotations: "warning"
