name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' # Specify .NET 8

    - name: Restore dependencies
      run: dotnet restore Testing.sln

    - name: Build
      run: dotnet build Testing.sln --no-restore

    - name: Run tests with coverage
      run: dotnet test Testing.sln --no-build --collect:"XPlat Code Coverage" /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./TestResults/

    - name: Verify test results directory
      run: find . -name TestResults -exec ls -la {} \;

    - name: List coverage files
      run: find . -name coverage.cobertura.xml

    - name: Find coverage file
      id: coverage-file
      run: echo "coverage_file=$(find . -name coverage.cobertura.xml)" >> $GITHUB_ENV

    - name: Free Code Coverage
      uses: SamuelCabralCruz/free-code-coverage@v0.0.13
      with:
        args: '--output-directory coverage' # Example argument, adjust as needed

    - name: List files in working directory
      run: ls -la

