name: Code Coverage

on: [push,pull_request]

jobs:
  base_branch_cov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x' # Specify the appropriate .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Run test coverage
        run: dotnet test --collect:"XPlat Code Coverage" /p:CoverletOutputFormat=lcov /p:CoverletOutput=./coverage/

      - name: List coverage directory
        run: ls -la ./coverage/

      - name: Upload code coverage for ref branch
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ref-lcov.info
          path: ./coverage/lcov.info

  checks:
    runs-on: ubuntu-latest
    needs: base_branch_cov
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x' # Specify the appropriate .NET version

      - name: Download code coverage report from base branch
        uses: actions/download-artifact@v3
        with:
          name: ref-lcov.info

      - name: Restore dependencies
        run: dotnet restore

      - name: Run test coverage
        run: dotnet test --collect:"XPlat Code Coverage" /p:CoverletOutputFormat=lcov /p:CoverletOutput=./coverage/

      - name: List coverage directory
        run: ls -la ./coverage/

      # Compares two code coverage files and generates a report as a comment
      - name: Generate Code Coverage report
        id: code-coverage
        uses: barecheck/code-coverage-action@v1
        with:
          barecheck-github-app-token: ${{ secrets.BARECHECK_GITHUB_APP_TOKEN }}
          lcov-file: "./coverage/lcov.info"
          base-lcov-file: "./ref-lcov.info"
          minimum-ratio: 0 # Fails GitHub action once code coverage is decreasing
          send-summary-comment: true
          show-annotations: "warning" # Possible options warning|error
