name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' # Specify .NET 8

    - name: Restore dependencies
      run: dotnet restore Testing.sln

    - name: Build
      run: dotnet build Testing.sln --no-restore

    - name: Run tests with coverage
      run: dotnet test Testing.sln --no-build --collect:"XPlat Code Coverage" /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./TestResults/

    - name: List all files and directories
      run: find . -type d -or -type f

    - name: Find coverage file
      id: coverage-file
      run: echo "coverage_file=$(find . -name coverage.cobertura.xml)" >> $GITHUB_ENV
      shell: bash

    - name: Set coverage file output
      run: echo "::set-output name=coverage_file::$(find . -name coverage.cobertura.xml)"
      id: set-coverage-file
      shell: bash

    - name: Print coverage file path
      run: echo "Coverage file path: ${{ steps.set-coverage-file.outputs.coverage_file }}"

    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Convert Cobertura to LCOV
      run: reportgenerator -reports:${{ steps.set-coverage-file.outputs.coverage_file }} -targetdir:./TestResults/ -reporttypes:lcov

    - name: Find LCOV file
      id: find-lcov-file
      run: echo "lcov_file=$(find ./TestResults/ -name coverage.lcov)" >> $GITHUB_ENV
      shell: bash

    - name: Set LCOV file output
      run: echo "::set-output name=lcov_file::$(find ./TestResults/ -name coverage.lcov)"
      id: set-lcov-file
      shell: bash

    - name: Print LCOV file path
      run: echo "LCOV file path: ${{ steps.set-lcov-file.outputs.lcov_file }}"

    - name: Generate Code Coverage report
      id: code-coverage
      uses: barecheck/code-coverage-action@v1
      with:
        barecheck-github-app-token: ${{ secrets.BARECHECK_GITHUB_APP_TOKEN }}
        lcov-file: ${{ steps.set-lcov-file.outputs.lcov_file }}
        base-lcov-file: ${{ steps.set-lcov-file.outputs.lcov_file }} # Adjust this if you have a base coverage file
        send-summary-comment: true
        show-annotations: "warning"
