name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' # Specify .NET 8

    - name: Restore dependencies
      run: dotnet restore Testing.sln

    - name: Build
      run: dotnet build Testing.sln --no-restore

    - name: Run tests with coverage
      run: dotnet test Testing.sln --no-build --collect:"XPlat Code Coverage" /p:CoverletOutputFormat=lcov /p:CoverletOutput=./coverage/

    - name: Verify test results directory
      run: find . -name TestResults -exec ls -la {} \;

    - name: List coverage files
      run: find . -name coverage.info

    - name: Debug: List all files in coverage directory
      run: ls -la ./coverage/

    - name: Find coverage file
      id: coverage-file
      run: echo "coverage_file=$(find . -name coverage.info)" >> $GITHUB_ENV

    - name: Code Coverage Report
      id: coverage-summary
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: ${{ env.coverage_file }}
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: true
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'

    - name: List files in working directory
      run: ls -la

    - name: Add Coverage PR Comment
      if: github.event_name == 'pull_request'
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        recreate: true
        path: code-coverage-results.md

    - name: Generate Code Coverage report
      id: code-coverage
      uses: barecheck/code-coverage-action@v1
      with:
        barecheck-github-app-token: ${{ secrets.BARECHECK_GITHUB_APP_TOKEN }}
        lcov-file: "./coverage/coverage.info"
        base-lcov-file: "./lcov.info"
        minimum-ratio: 0 # Fails Github action once code coverage is decreasing
        send-summary-comment: true
        show-annotations: "warning" # Possible options warning|error
