name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --no-restore

      - name: Run tests with coverage
        run: dotnet test --no-build --collect:"XPlat Code Coverage"

      - name: Upload code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: '**/TestResults/*/coverage.cobertura.xml'

      - name: Generate code coverage report
        uses: FreeCoverlet/Free-Code-Coverage@v1
        with:
          coverageFiles: '**/TestResults/*/coverage.cobertura.xml'
