name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' # Specify .NET 8

    - name: Restore dependencies
      run: dotnet restore Testing.sln

    - name: Build
      run: dotnet build Testing.sln --no-restore

    - name: Run tests with coverage
      run: dotnet test Testing.sln --no-build --collect:"XPlat Code Coverage" /p:CoverletOutputFormat=lcov /p:CoverletOutput=./coverage/

    - name: Find coverage file
      id: coverage-file
      run: echo "coverage_file=$(find . -name coverage.info)" >> $GITHUB_ENV

    - name: Generate Code Coverage report
      id: code-coverage
      uses: barecheck/code-coverage-action@v1
      with:
        barecheck-github-app-token: ${{ secrets.BARECHECK_GITHUB_APP_TOKEN }}
        lcov-file: "./coverage/coverage.info"
        base-lcov-file: "./lcov.info"
        minimum-ratio: 0 # Fails Github action once code coverage is decreasing
        send-summary-comment: true
        show-annotations: "warning" # Possible options warning|error
